### ISSUE TITLE
Section 3 - No padding on bottom of image gallery

### ISSUE THREAD

**Issue by josh76543210** [josh76543210/Collaboration---Frontend-Mentor---Loopstudios-landing-page-solution#13]
## Description
There is no space separating the bottom of section 3 from the footer. The problem only occurs on screen sizes larger than 800px.

## Screenshot
![Screenshot 2023-11-06 at 14-50-27 Frontend Mentor Loopstudios landing page](https://github.com/josh76543210/Collaboration---Frontend-Mentor---Loopstudios-landing-page-solution/assets/119835493/4d6f33fc-a2ef-4b4b-a52f-0e86f5fe6e2e)

**Comment by Leroy-sama** [comment]
I'm resolving this issue

**Comment by Leroy-sama** [comment]
Just about to submit a PR

**Comment by josh76543210** [comment]
Resolved with PR #20
