### ISSUE TITLE
Section 2 max-width

### ISSUE THREAD

**Issue by josh76543210** [josh76543210/Collaboration---Frontend-Mentor---Loopstudios-landing-page-solution#16]
## Description
The width for section 2 does not match the width for section 1 and 3. The issue is visible on screen sizes larger than 690px.

## Screenshot
![Screenshot 2023-11-07 at 08-26-43 Frontend Mentor Loopstudios landing page](https://github.com/josh76543210/Collaboration---Frontend-Mentor---Loopstudios-landing-page-solution/assets/119835493/38d983d5-2b1d-4c09-93e2-df44e9268665)

**Comment by Leroy-sama** [comment]
section 2 max-width issue

**Comment by josh76543210** [comment]
Resolved with #21
